"""Minimal stubs for notebooklm.exceptions."""

class NotebookLMError(Exception): ...
class AuthError(NotebookLMError): ...
class RateLimitError(NotebookLMError): ...
class RPCError(NotebookLMError): ...
class RPCTimeoutError(RPCError): ...
class NetworkError(NotebookLMError): ...
class ServerError(NotebookLMError): ...
class ClientError(NotebookLMError): ...
class ConfigurationError(NotebookLMError): ...
class ValidationError(NotebookLMError): ...
class NotebookNotFoundError(NotebookLMError): ...
class SourceNotFoundError(NotebookLMError): ...
class ArtifactError(NotebookLMError): ...
class ArtifactNotFoundError(ArtifactError): ...
class ArtifactNotReadyError(ArtifactError): ...
class ArtifactDownloadError(ArtifactError): ...
class ArtifactParseError(ArtifactError): ...
class SourceError(NotebookLMError): ...
class SourceAddError(SourceError): ...
class SourceProcessingError(SourceError): ...
class SourceTimeoutError(SourceError): ...
class ChatError(NotebookLMError): ...
class DecodingError(NotebookLMError): ...
class UnknownRPCMethodError(NotebookLMError): ...
