"""GitHub Pages setup: player page, README links, and auto-enable."""

from __future__ import annotations

import html as html_mod
import importlib.resources
import json
import os
import re
import subprocess
import urllib.error
import urllib.request
from pathlib import Path

from repo_artefacts.console import get_console
from repo_artefacts.exceptions import GitRemoteError

_ARTEFACT_ROWS = {
    "audio": "| 🎧 **[Listen to the Audio Overview]({base_url})** | Two AI hosts discuss the project — great for commutes |",
    "video": "| 🎬 **[Watch the Video Overview]({base_url}#video)** | Visual walkthrough of architecture and concepts |",
    "infographic": "| 🖼️ **[View the Infographic]({base_url}#infographic)** | Architecture and flow at a glance |",
    "slides": "| 📊 **[Browse the Slide Deck]({base_url}#slides)** | Presentation-ready project overview |",
}


def _build_readme_block(base_url: str, available: set[str]) -> str:
    """Build the README artefacts block with only available artefact types."""
    rows = "\n".join(
        row.format(base_url=base_url) for kind, row in _ARTEFACT_ROWS.items() if kind in available
    )
    return (
        "<!-- ARTEFACTS:START -->\n"
        "## Generated Artefacts\n"
        "\n"
        "> 🔍 **Explore this project** — AI-generated overviews via "
        "[Google NotebookLM](https://notebooklm.google.com)\n"
        "\n"
        "| | |\n"
        "|---|---|\n"
        f"{rows}\n"
        "\n"
        "*Generated by [notebooklm-repo-artefacts]"
        "(https://github.com/NetDevAutomate/notebooklm-repo-artefacts)*\n"
        "<!-- ARTEFACTS:END -->"
    )


def get_github_info(repo_root: Path) -> tuple[str, str]:
    """Extract org/repo from git remote."""
    out = subprocess.check_output(["git", "remote", "-v"], cwd=repo_root, text=True)
    for line in out.splitlines():
        m = re.search(r"github\.com[:/]([^/]+)/([^/\s]+?)(?:\.git)?(?:\s|$)", line)
        if m:
            return m.group(1), m.group(2)
    raise GitRemoteError("No GitHub remote found. Use --org and --repo.")


def get_github_token() -> str | None:
    """Resolve GITHUB_TOKEN: env → age-encrypted tokens → macOS Keychain → 1Password CLI."""
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        return token

    # age-encrypted tokens file
    age_file = Path.home() / ".config" / "secrets" / "tokens.age"
    age_key = Path.home() / ".config" / "age" / "keys.txt"
    if age_file.exists() and age_key.exists():
        try:
            out = subprocess.check_output(
                ["age", "-d", "-i", str(age_key), str(age_file)],
                text=True,
                stderr=subprocess.DEVNULL,
            )
            for line in out.splitlines():
                m = re.match(r'^export GITHUB_TOKEN="(.+)"$', line)
                if m:
                    get_console().print("[green]✓[/green] GITHUB_TOKEN loaded from tokens.age")
                    return m.group(1)
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass

    # macOS Keychain
    try:
        token = subprocess.check_output(
            [
                "security",
                "find-generic-password",
                "-a",
                "GITHUB_TOKEN",
                "-s",
                "api-keys",
                "-w",
            ],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if token:
            get_console().print("[green]✓[/green] GITHUB_TOKEN loaded from macOS Keychain")
            return token
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    # 1Password CLI
    try:
        items = subprocess.check_output(
            ["op", "item", "list", "--vault", "API_KEYS", "--format", "json"],
            text=True,
            stderr=subprocess.DEVNULL,
        )
        for item in json.loads(items):
            if item.get("title") == "GITHUB_TOKEN":
                detail = subprocess.check_output(
                    [
                        "op",
                        "item",
                        "get",
                        item["id"],
                        "--reveal",
                        "--format",
                        "json",
                        "--vault",
                        "API_KEYS",
                    ],
                    text=True,
                    stderr=subprocess.DEVNULL,
                )
                for field in json.loads(detail).get("fields", []):
                    if field.get("label") == "credential" and field.get("value"):
                        get_console().print("[green]✓[/green] GITHUB_TOKEN loaded from 1Password")
                        return field["value"]
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    return None


def _has_gh_pages_branch(org: str, repo: str, headers: dict[str, str]) -> bool:
    """Check if the repo has a gh-pages branch."""
    url = f"https://api.github.com/repos/{org}/{repo}/branches/gh-pages"
    req = urllib.request.Request(url, headers=headers)
    try:
        urllib.request.urlopen(req)
        return True
    except urllib.error.HTTPError:
        return False


def enable_github_pages(org: str, repo: str) -> bool:
    """Enable GitHub Pages via API, preserving existing config."""
    token = get_github_token()
    if not token:
        get_console().print("[yellow]⚠ GITHUB_TOKEN not set — enable Pages manually[/yellow]")
        return False

    url = f"https://api.github.com/repos/{org}/{repo}/pages"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    # Check if already enabled — if so, leave config untouched
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req) as resp:
            config = json.loads(resp.read())
            source = config.get("source", {})
            branch = source.get("branch", "?")
            path = source.get("path", "?")
            get_console().print(
                f"[green]✓[/green] GitHub Pages already enabled ({branch} → {path})"
            )
        return True
    except urllib.error.HTTPError as e:
        if e.code != 404:
            get_console().print(f"[yellow]⚠ GitHub Pages check failed: {e.code}[/yellow]")
            return False

    # Not yet enabled — prefer gh-pages branch if it exists
    if _has_gh_pages_branch(org, repo, headers):
        source_cfg = {"branch": "gh-pages", "path": "/"}
        label = "gh-pages → /"
    else:
        source_cfg = {"branch": "main", "path": "/docs"}
        label = "main → /docs"

    data = json.dumps({"source": source_cfg}).encode()
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    req.add_header("Content-Type", "application/json")
    try:
        urllib.request.urlopen(req)
        get_console().print(f"[green]✓[/green] GitHub Pages enabled ({label})")
        return True
    except urllib.error.HTTPError as e:
        get_console().print(f"[yellow]⚠ Failed to enable Pages: {e.code}[/yellow]")
        return False


def setup_pages(
    repo_root: Path,
    org: str,
    repo: str,
    store_base_url: str | None = None,
    available_artefacts: set[str] | None = None,
) -> str:
    """Create player page, update README, enable GitHub Pages. Returns player URL.

    Args:
        store_base_url: If provided, use this URL for README links and skip
            writing index.html / enabling Pages on the source repo (the store
            handles both).
        available_artefacts: Override artefact detection (used with store mode
            where artefacts aren't in docs/artefacts/).
    """
    if store_base_url:
        # Store mode: only update README with store URLs
        base_url = store_base_url
        available = available_artefacts or set()
    else:
        # Local mode: write player page, detect artefacts, enable Pages
        artefacts_dir = repo_root / "docs" / "artefacts"
        artefacts_dir.mkdir(parents=True, exist_ok=True)

        html_content = (
            importlib.resources.files("repo_artefacts").joinpath("template.html").read_text()
        )
        html_content = html_content.replace("{REPO_NAME}", html_mod.escape(repo, quote=True))
        (artefacts_dir / "index.html").write_text(html_content)
        get_console().print("[green]✓[/green] Created docs/artefacts/index.html")

        base_url = f"https://{org.lower()}.github.io/{repo}/artefacts/"
        from repo_artefacts.publish import check_artefacts

        available = available_artefacts or set(check_artefacts(artefacts_dir))

    # Update README (both local and store modes)
    readme = repo_root / "README.md"
    if readme.exists():
        text = readme.read_text()
        block = _build_readme_block(base_url, available)
        if "<!-- ARTEFACTS:START -->" in text:
            text = re.sub(
                r"<!-- ARTEFACTS:START -->.*?<!-- ARTEFACTS:END -->",
                block,
                text,
                flags=re.DOTALL,
            )
            get_console().print("[green]✓[/green] Updated artefacts block in README.md")
        else:
            text = text.rstrip() + "\n\n" + block + "\n"
            get_console().print("[green]✓[/green] Appended artefacts block to README.md")
        readme.write_text(text)

    if not store_base_url:
        enable_github_pages(org, repo)

    return base_url
