"""GitHub Pages setup: player page, README links, and auto-enable."""

from __future__ import annotations

import importlib.resources
import json
import os
import re
import subprocess
import urllib.error
import urllib.request
from pathlib import Path

from rich.console import Console

console = Console()

README_BLOCK = """\
<!-- ARTEFACTS:START -->
## Repo Deep Dive

> 🔍 **Explore this project** — AI-generated overviews via [Google NotebookLM](https://notebooklm.google.com)

| | |
|---|---|
| 🎧 **[Listen to the Audio Overview]({base_url})** | Two AI hosts discuss the project — great for commutes |
| 🎬 **[Watch the Video Overview]({base_url}#video)** | Visual walkthrough of architecture and concepts |
| 🖼️ **[View the Infographic]({base_url}#infographic)** | Architecture and flow at a glance |
| 📊 **[Browse the Slide Deck]({base_url}#slides)** | Presentation-ready project overview |

*Generated by [notebooklm-repo-artefacts](https://github.com/andytaylor/notebooklm-repo-artefacts)*
<!-- ARTEFACTS:END -->"""


def get_github_info(repo_root: Path) -> tuple[str, str]:
    """Extract org/repo from git remote."""
    out = subprocess.check_output(["git", "remote", "-v"], cwd=repo_root, text=True)
    for line in out.splitlines():
        m = re.search(r"github\.com[:/]([^/]+)/([^/\s]+?)(?:\.git)?(?:\s|$)", line)
        if m:
            return m.group(1), m.group(2)
    raise SystemExit("No GitHub remote found. Use --org and --repo.")


def get_github_token() -> str | None:
    """Resolve GITHUB_TOKEN: env → age-encrypted tokens → macOS Keychain → 1Password CLI."""
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        return token

    # age-encrypted tokens file
    age_file = Path.home() / ".config" / "secrets" / "tokens.age"
    age_key = Path.home() / ".config" / "age" / "keys.txt"
    if age_file.exists() and age_key.exists():
        try:
            out = subprocess.check_output(
                ["age", "-d", "-i", str(age_key), str(age_file)],
                text=True,
                stderr=subprocess.DEVNULL,
            )
            for line in out.splitlines():
                m = re.match(r'^export GITHUB_TOKEN="(.+)"$', line)
                if m:
                    console.print(
                        "[green]✓[/green] GITHUB_TOKEN loaded from tokens.age"
                    )
                    return m.group(1)
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass

    # macOS Keychain
    try:
        token = subprocess.check_output(
            [
                "security",
                "find-generic-password",
                "-a",
                "GITHUB_TOKEN",
                "-s",
                "api-keys",
                "-w",
            ],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if token:
            console.print("[green]✓[/green] GITHUB_TOKEN loaded from macOS Keychain")
            return token
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    # 1Password CLI
    try:
        items = subprocess.check_output(
            ["op", "item", "list", "--vault", "API_KEYS", "--format", "json"],
            text=True,
            stderr=subprocess.DEVNULL,
        )
        for item in json.loads(items):
            if item.get("title") == "GITHUB_TOKEN":
                detail = subprocess.check_output(
                    [
                        "op",
                        "item",
                        "get",
                        item["id"],
                        "--reveal",
                        "--format",
                        "json",
                        "--vault",
                        "API_KEYS",
                    ],
                    text=True,
                    stderr=subprocess.DEVNULL,
                )
                for field in json.loads(detail).get("fields", []):
                    if field.get("label") == "credential" and field.get("value"):
                        console.print(
                            "[green]✓[/green] GITHUB_TOKEN loaded from 1Password"
                        )
                        return field["value"]
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    return None


def enable_github_pages(org: str, repo: str) -> bool:
    """Enable GitHub Pages (main branch, /docs folder) via API."""
    token = get_github_token()
    if not token:
        console.print("[yellow]⚠ GITHUB_TOKEN not set — enable Pages manually[/yellow]")
        return False

    url = f"https://api.github.com/repos/{org}/{repo}/pages"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    # Check if already enabled
    req = urllib.request.Request(url, headers=headers)
    try:
        urllib.request.urlopen(req)
        console.print("[green]✓[/green] GitHub Pages already enabled")
        return True
    except urllib.error.HTTPError as e:
        if e.code != 404:
            console.print(f"[yellow]⚠ GitHub Pages check failed: {e.code}[/yellow]")
            return False

    # Enable it
    data = json.dumps({"source": {"branch": "main", "path": "/docs"}}).encode()
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    req.add_header("Content-Type", "application/json")
    try:
        urllib.request.urlopen(req)
        console.print("[green]✓[/green] GitHub Pages enabled (main → /docs)")
        return True
    except urllib.error.HTTPError as e:
        console.print(f"[yellow]⚠ Failed to enable Pages: {e.code}[/yellow]")
        return False


def setup_pages(repo_root: Path, org: str, repo: str) -> str:
    """Create player page, update README, enable GitHub Pages. Returns player URL."""
    artefacts_dir = repo_root / "docs" / "artefacts"
    artefacts_dir.mkdir(parents=True, exist_ok=True)

    # Write player page
    html = (
        importlib.resources.files("repo_artefacts")
        .joinpath("template.html")
        .read_text()
    )
    html = html.replace("{REPO_NAME}", repo)
    (artefacts_dir / "index.html").write_text(html)
    console.print("[green]✓[/green] Created docs/artefacts/index.html")

    # Update README
    base_url = f"https://{org.lower()}.github.io/{repo}/artefacts/"
    readme = repo_root / "README.md"
    if readme.exists():
        text = readme.read_text()
        block = README_BLOCK.format(base_url=base_url)
        if "<!-- ARTEFACTS:START -->" in text:
            text = re.sub(
                r"<!-- ARTEFACTS:START -->.*?<!-- ARTEFACTS:END -->",
                block,
                text,
                flags=re.DOTALL,
            )
            console.print("[green]✓[/green] Updated artefacts block in README.md")
        else:
            text = text.rstrip() + "\n\n" + block + "\n"
            console.print("[green]✓[/green] Appended artefacts block to README.md")
        readme.write_text(text)

    enable_github_pages(org, repo)
    return base_url
