"""Update a README.md with a dynamic listing of artefacts in docs/artefacts/."""

from pathlib import Path

from rich.console import Console

console = Console()

ARTEFACT_NAMES = {
    "audio_overview": "🎧 Audio Overview",
    "video_overview": "🎬 Video Overview",
    "slides": "📊 Slide Deck",
    "infographic": "🖼️ Infographic",
}

SKIP_SUFFIXES = {".md"}  # Skip collected markdown source files

MARKER_START = "<!-- ARTEFACTS:START -->"
MARKER_END = "<!-- ARTEFACTS:END -->"


def update_readme_artefacts(
    readme_path: Path,
    artefacts_dir: Path,
) -> None:
    """Update the artefacts section in a README.md.

    Looks for markers <!-- ARTEFACTS:START --> and <!-- ARTEFACTS:END -->
    and replaces everything between them with a listing of files in
    the artefacts directory.

    If markers don't exist, appends the section to the end of the file.
    """
    if not artefacts_dir.is_dir():
        console.print(f"[yellow]No artefacts directory at {artefacts_dir}[/yellow]")
        return

    # Collect artefacts (skip .md source files and the content PDF)
    files = sorted(
        f for f in artefacts_dir.iterdir()
        if f.is_file() and f.suffix not in SKIP_SUFFIXES and not f.stem.endswith("_content")
    )

    # Build the section content
    lines = [MARKER_START, "## Generated Artefacts", ""]
    if files:
        rel_dir = artefacts_dir
        try:
            rel_dir = artefacts_dir.relative_to(readme_path.parent)
        except ValueError:
            pass

        for f in files:
            # Match by filename prefix for label
            label = "📎 File"
            for prefix, name in ARTEFACT_NAMES.items():
                if f.stem.startswith(prefix):
                    label = name
                    break
            rel_path = f"{rel_dir}/{f.name}"
            lines.append(f"- {label}: [{f.name}]({rel_path})")
        lines.append("")
        lines.append(f"*Generated by [notebooklm-repo-artefacts](https://github.com/andytaylor/notebooklm-repo-artefacts) via Google NotebookLM.*")
    else:
        lines.append("No artefacts generated yet. Run `repo-artefacts generate` to create them.")

    lines.append(MARKER_END)
    section = "\n".join(lines)

    # Read existing README
    if not readme_path.is_file():
        console.print(f"[red]README not found at {readme_path}[/red]")
        return

    content = readme_path.read_text(encoding="utf-8")

    # Replace between markers or append
    if MARKER_START in content and MARKER_END in content:
        start_idx = content.index(MARKER_START)
        end_idx = content.index(MARKER_END) + len(MARKER_END)
        content = content[:start_idx] + section + content[end_idx:]
    else:
        content = content.rstrip() + "\n\n" + section + "\n"

    readme_path.write_text(content, encoding="utf-8")
    console.print(f"[green]✓[/green] Updated {readme_path} with {len(files)} artefacts")
